### ISSUE TITLE
Sponsor packages

### ISSUE THREAD

**Issue by giedriusr** [euruko2013/general#1]
Do we know the packages for sponsors or we have to come up with that? Did dutch guys send us the docs already? I'd like to talk to one potential sponsor, but I need to know more details.

**Comment by damphyr** [comment]
We're getting the material from ams.rb soon. 
We then need to have a rough budget and for that we need the venue shortlist (@teoulas is on it). 
No definite date though, it's all fire and forget at the moment with summer holidays looming.

**Comment by giedriusr** [comment]
Great. Regarding the venues, I was thinking about it, but nothing came in my mind. In the center of Athens, only hotels are the only possibility with huge conference halls. Unless I didn't discover secret places of Athens yet.

**Comment by giedriusr** [comment]
Ok, I believe we are going to have different kind of sponsorship as we had in Euruko Amsterdam.
- standard sponsors
- party sponsors
- lunch / coffee sponsors

So for one of the parties, I have a sponsor already.

Will be waiting for detailed information about sponsor packages.

**Comment by pagojo** [comment]
Great, ok we will keep everyone posted soon.

**Comment by teoulas** [comment]
Ideas:
https://github.com/euruko2013/general/wiki/Sponsors%3F

**Comment by pagojo** [comment]
We also have the details from the Amsterdam EuRuKo packages that the EuRuKo 2012 team shared with us :-)

**Comment by teoulas** [comment]
Can we put them up to some wiki page or issue?

**Comment by chief** [comment]
Great news! kudos @pagojo

**Comment by fotos** [comment]
@giedriusr feel free to point potential sponsors to the [EuRuKo 2013 website](http://euruko2013.org/#sponsors) or ask them to send inquiries via email to **sponsors at euruko2013.org**. Thanks!

Closing this issue.
