### ISSUE TITLE
Volunteer for asking sponsors for networking of the event

### ISSUE THREAD

**Issue by dark5un** [euruko2013/general#27]

**Comment by nikosd** [comment]
When you say networking you mean internet networking or social networking? Sorry, I didn't get it completely :)

**Comment by dark5un** [comment]
Errr yes you are right... I was talking about internet networking... :-P

**Comment by giedriusr** [comment]
Meaning, that u're volunteering to find sponsors through networking? Sometimes it's really hard to get the idea, please try to add more descriptive descriptions for stupid people like me :)

**Comment by pagojo** [comment]
I'd call it computer networking but anyway.

Any  news @dark5un btw?

**Comment by dark5un** [comment]
I have contacted unofficialy HOL, Forthnet, Cyta, Cosmote. I am expecting news and official contact info next week.

**Comment by nikosd** [comment]
:thumbsup:

P.S.: Vodafon & Wind?

**Comment by damphyr** [comment]
It would be nice if one of the mobile phone providers would sponsor us with a data plan offer instead (sim cards for delegates with a month of unlimited 3G data for something like 20€?).

**Comment by pagojo** [comment]
Closing this for now as @dark5un is on it. We will open new tickets for specific help that we will need.
