### ISSUE TITLE
Research and market comparison for ticketing service

### ISSUE THREAD

**Issue by pagojo** [euruko2013/general#29]
The organising committee is looking for a ticketing service. Does anyone care to make recommendations or share experiences from services they've used?
# What do we want?

Gather a list of online ticketing services like [Eventora](https://www.eventora.com/), [Eventbrite](http://www.eventbrite.com/), etc alongside the following data :
- Pricing
- Previous experience with high profile events
- Available payment methods
- Location
- Main extra features

**Comment by nikosd** [comment]
Updated issue with a little bit more thorough description.

**Comment by nikosd** [comment]
Since no-one volunteered this is already handled by the committee and thus closing it.
