### ISSUE TITLE
Venues

### ISSUE THREAD

**Issue by fotos** [euruko2013/general#4]
# Into

This is an attempt to right down some venue requirements as well as some proposals for venues in Athens.

Lets ignite the venue discussion!
# Requirements

A short list of requirements in no specific order.
- **Adequate capacity**: 500 to 600 delegates, single track event, lots of people in one place at the same time
- **Accessible**: near metro stations, downtown, within walking distance from hotels
- **Available**: the earlier we book the better
- **Affordable**: the venue shouldn't cost a fortune, we should be able to get by with sponsorships / tickets
- **Cool place**: cozy, relaxed atmosphere while aesthetically pleasant for hipsters and Intstagram aficionados
- **Technical requirements**: Good acoustics, A/V equipment, outlets, [WiFi](http://serverfault.com/questions/72767/why-is-internet-access-and-wi-fi-always-so-terrible-at-large-tech-conferences) [setup](http://www.nonblocking.io/2011/05/how-to-make-wifi-work-at-tech.html), [coverage](http://www.joelonsoftware.com/items/2009/10/08.html) and [support](http://www.tummy.com/Community/Articles/pycon2009-network/), large backhaul, broadcasting / streaming capability
- **Other**: facilities (e.g. cloakroom, parking), promotional ability (banners), catering capabilities, health & safety requirements
# Venues
## [Hellenic Cosmos (Theatron)  - Ελληνικός Κόσμος (Θέατρον)](http://www.theatron254.gr)
- Pros:
  1. Successfully hosted the [TEDxAthens](http://2011.tedxathens.com) event in 2011
  2. Satisfies most technical requirements
- Cons:
  1. Accessible only by car or walk some distance from Green line [Kallithea station](http://goo.gl/maps/yAyV)
  2. ~~Adequate capacity (?)~~ (**UPDATE:** yes it can [accommodate around 1.000 delegates](http://www.pireos254.gr/gr/antigone.html))
  3. Affordable (?)
  4. No hotels nearby (?)
## [Athens Concert Hall - Μέγαρο Μουσικής](http://www.megaron.gr)
- Pros:
  1. Easily accesible with the underground (Blue line)
  2. Direct connection with the airport ([Blue line](http://goo.gl/maps/l8NC))
  3. Near hotels ([Hilton](http://www.hiltonathens.gr), [Divani Caravel](http://www.divanis.com/caravel/))
  4. Big facade where we could hang a _huge_ banner to promote the event
  5. Many halls / auditoria to choose from (like the [Trianti Hall](http://www.maicc.gr/en/explore/auditoria/trianti-hall),  [Hall plans - PDF](http://www.maicc.gr/uploads/docs/MAICC_PLANS_en.pdf))
  6. Parking facilities
- Cons:
  1. Expensive
- More info http://www.maicc.gr
## [Technopolis - Τεχνόπολης](http://www.technopolis-athens.com)
- Pros:
  1. Affordable, perhaps the municipality can provide the place for free
  2. Cool place, inspiring, all the machinery gives away a tech feeling
-  Cons:
  1. Accessibility, 10 minutes walk from Green line station Thiseio
  2. Too small: there is an auditorium but it might be too small (**UPDATE**: it's [250 seats](http://www.technopolis-athens.com/web/guest/visitors/buldings?p_p_id=bs_event_locations&p_p_action=1&p_p_state=normal&p_p_mode=view&p_p_col_id=column-2&p_p_col_count=1&_bs_event_locations_struts_action=%2Fext%2Feventlocations%2FloadRoom&_bs_event_locations_loadaction=view&_bs_event_locations_mainid=14))
  3. Availability: high season for open spaces like Technopolis
## [Benaki Museum - Μουσείο Μπενάκι](http://www.benaki.gr)
- Pros:
  1. Hosts [OpenCoffee](http://opencoffee.gr) events
  2. Cool place to hang around, nearby booming Gazi
- Cons:
  1. Adequate capacity (?)
  2. Technical capabilities (?)
  3. Same accessibility as Technopolis
## [Helexpo Conference Center - Συνεδριακό Κέντρο Helexpo](http://www.helexpo.gr/default.aspx?lang=el-GR&loc=1&page=607)
- Pros:
  1. Affordable (?)
  2. Accessible by two lines, suburban to the airport, Green line to city center
- Cons:
  1. Accessibility, long walking distance from the nearest metro station
  2. Loses on the coolness factor, not a really nice place to be
## [Metropolitan](http://www.metropolitanexpo.gr/)
- Pros:
  1. Accessible, next to the airport, direct connection with downtown
  2. Flexible capacity
  3. Technically sufficient
- Cons:
  1. Too far away from the city center
## ~~[Eugenides Foundation - Ευγενίδιο Ίδρυμα](http://www.eugenfound.edu.gr/)~~

  **UPDATE**: Nope, [no central stage](http://www.eugenfound.edu.gr/frontoffice/portal.asp?cpage=NODE&cnode=184) available 
## [Athinais - Αθηναΐς](http://www.athinais.com.gr)
- Pros:
- Cons:
## [Olympic Venues - Ολυμπιακές Εγκαταστάσεις](http://www.etasa.gr/page.aspx?itemID=SPG296)

Are there any Olympic Venues near the beach (southern suburbs) suitable for hosting a conference? It would be awesome if we managed to combine the sea breeze, the golden sand and the soothing Greek sun with some Ruby talks!
# Outro

Feel free to comment on the venues, their characteristics, share experiences from other conferences / events hosted in any of the above or propose others. Choosing the right venue for the event is extremely crucial!

PS. Perhaps this should be moved to the Wiki and then use this issue as a place to accept more ideas / proposals?

**Comment by teoulas** [comment]
Good stuff. I have already compiled a list and we have some common ones.
I'll add yours too and make a wiki page.
On Jun 30, 2012 4:28 AM, "Fotos Georgiadis" <
reply@reply.github.com>
wrote:

**Comment by stream7** [comment]
Regarding Benaki Museum's capacity. I believe the hall that opencoffee takes place can accomodate up to ~400 people.
It has 15 rows with 25 seats each and some free space for extra chairs.

**Comment by teoulas** [comment]
I uploaded a wiki page with some Venues I had gathered in a google spreadsheet:
https://github.com/euruko2013/general/wiki/Venues

**Comment by nikosd** [comment]
Regarding "Hellenic Cosmos" my sister works there so I could get some direct connections inside :)

**Comment by giedriusr** [comment]
All these cinema places, 600 capacity is for one room? Since we want to host more than 600 attendees, not many places to choose from.

**Comment by giedriusr** [comment]
The Badminton place is just awesome! And capacity is more than enough :))

**Comment by damphyr** [comment]
Keep in mind that we need 2 spaces: the room where we watch the presentations and a space for coffee and hanging out.

**Comment by vvatikiotis** [comment]
The Atrium of the Muses & Muses Foyer @ Megaron. The EACL 2009 was hosted there, around 500 ppl.

**Comment by fotos** [comment]
Where are we with the venue hunting? Did we approach venue managers and asked prices / facilities / availabilities? Did we go to an event organizer and he's doing the dirty work for us?

**Comment by pagojo** [comment]
We've spoken during August with 5 event management contractors and were planning to meet them and interview them end of September! :-)

If anyone wants to come over during the process please say so. Skroutz were kind enough to have given us their premisses for a day to do so, therefore we have to ask for their permission if we are to invite more observers but I can't see this being a problem right now unless too many wanna pop in.

**Comment by fotos** [comment]
What a great coincidence! I happen to be on Skroutz premises too! :astonished:

Thanks for the update. Keep us posted when the meetings get arranged.

**Comment by nikosd** [comment]
Stay tuned for final venue announcement very soon!

**Comment by nikosd** [comment]
The venue is by 99% finalized. Closing this issue and soon we will hopefully have an announcement.
