### ISSUE TITLE
T-shirts for the conference

### ISSUE THREAD

**Issue by giedriusr** [euruko2013/general#6]
Definitely, we are going to have Ruby Conf t-shirts. Are we going to ask sizes of the attendees? Cause I think, AMS just made random sizes, though I am not sure. If I get more details on that, I know the place which might be interested in making them. I believe we will need around 600 - 650 t-shirts on that day.

What are your thoughts?

**Comment by giedriusr** [comment]
p.s. I believe I don't have permissions to add label for this issue, but it should be under Question as well.

**Comment by pagojo** [comment]
We could have a filed in the ticketing system where at the time of the purchase delegates can say whether they need one and if they do they should specify their size and pay a bit extra. If Eventora can handle it for example then it shouldn't be too difficult.

**Comment by giedriusr** [comment]
I thought this is going to be covered from the price for the ticket.

**Comment by pagojo** [comment]
I don't know what others think but we shouldn't tax someone's ticket with the cost of a t-shirt that may not be needed.

I'm of the view that the ticket price should be as low as possible and anything else should come as extra.

What do others think?

**Comment by giedriusr** [comment]
I agree, but do we know then, how AMS did regarding the t-shirts? What is the primary idea regarding the price for ticket. For this amount of money, which expenses are we covering?

**Comment by pagojo** [comment]
There is going to be a full budget and cost breakdown published of course! :-)

**Comment by giedriusr** [comment]
:+1:

**Comment by mikedi** [comment]
Did anybody think to include a few girl T-shirts?

**Comment by pagojo** [comment]
What are 'girl t-shirts'  other than perhaps of a smaller size? :-)

**Comment by petros** [comment]
Maybe pink?

**Comment by mikedi** [comment]
'Girl T-shirts' = smaller size + lower neck lines. 
Color is not an issue.
How about a logo: "Ruby is a girl's best friend" Paraphrasing the song "Diamonds are a girl's best friend" 
Too much maybe?

**Comment by pagojo** [comment]
not a bad idea :-)

Thanks for the clarification as to what makes a girl's t-shirt (d'ohh @amiridis ..pink!? :o)

**Comment by petros** [comment]
I like pink. I don't know what is your problem :P

**Comment by pagojo** [comment]
I like pink but pink is not ruby.... (shall we stop the pun know?:-)
