### ISSUE TITLE
Event management

### ISSUE THREAD

**Issue by pagojo** [euruko2013/general#8]
Please if you know of any event management outfit, that wishes to participate in the EuRuKo 2013 RFP to win the contract, let them contact us asap.

**Comment by mikedi** [comment]
When you say event management outfit what exactly do you mean? 
Are there the event requirements somewhere I can send to event management companies?
I can only locate the venue requirements.
Greetings and Salutations

**Comment by pagojo** [comment]
The event spec is not finalised yet, but if you do know of any event management folk that could potentially take up the organisation of the gig then please ask them to contact us, or give us their details and we will.

Broad spec is something like:

"We need an event management outfit to help us run a single-track 2 day tech event in Athens which will to host 600+ delegates in a  central location close to public transportation and amenities. No PR work is necessary for them as the event is usually sold out in 2 minutes!"

If this isn'y enough to get them excited or if they don't get the above then most likely we don't want to work with them.

thanks btw :-)

**Comment by florak** [comment]
I'm interested in organizing the event, as I have done studies in that field and I have worked in similar positions. However, I can only work part-time on that project, due to my day job. Thus, I would like you to inform me on more details, such as when I should start preparing for the project, what your expectations for that project are etc.
Thank you in advance for your reply.
Flora

**Comment by mikedi** [comment]
Despoina Tzouma from Speira Arts & Media is interested to organize the event. I told her the basics. 600 computer geeks. Good WIFI. 31 May-1st June. She needs more info though. You can contact her at ... (details removed to protect her from spam)
Cheers.

**Comment by pagojo** [comment]
@florak This is going to be a full time job for the contractor that does it for us. However we are very much interested in your insight. Could you possibly meet us at the next Athens Ruby Meetup in September? maybe follow GreekRubyMeetup on Twitter to find out when this is going to be?

@mikedi Cheers! Will contact her :-)

**Comment by pagojo** [comment]
Contacted Despoina

**Comment by pagojo** [comment]
@mikedi  Apparently that email you gave us is invalid according to yahoo :-/

**Comment by mikedi** [comment]
I called her, the email is: (removed to protect from spam)

**Comment by pagojo** [comment]
Cheers, resending email....

**Comment by cedel** [comment]
Greetings, got another contact from a friend of mine. Here are the contact details:

Nikos Athanasopoulos
Sales and Business Development Manager

Στέγη Γραμμάτων & Τεχνών Ιδρύματος Ωνάση
Onassis Cultural Centre, Athens
Γαλαξία 2 & Ευρυδάμαντος, 11745
t. + 30 213 0178040
f. +30 210 9249093 κινητό 6974 909069
www.sgt.gr

**Comment by pagojo** [comment]
@cedel thanks

**Comment by giedriusr** [comment]
Any news about priority 1?

**Comment by pagojo** [comment]
Yup, we've contacted 5 event management contractors so far and we will set a date to meet them and see their presentation in mid-September

**Comment by giedriusr** [comment]
Cool! Great news!

**Comment by giedriusr** [comment]
Any news? It's about mid Sept

**Comment by pagojo** [comment]
The committee invites whoever is interested to attend the event management contractor presentations that will be held (in greek:-) on Saturday the 29th of September at the premisses of Skroutz.gr (who have been so kind). 

If you do intend to attend you _MUST_ tell us beforehand in order to inform Skroutz and their security staff. Skroutz reserve the right to refuse entrance though, so please be prompt and tell us so ASAP. If you decide to come over  you'll have to be there at 12pm sharp and stay for about a hours.

**Comment by giedriusr** [comment]
I won't be able to participate, just trying to follow the organizing stuff. Mostly will try to help remotely, because I left Greece 3 weeks ago.

**Comment by pagojo** [comment]
ouch for how long @giedriusr ?

**Comment by giedriusr** [comment]
I moved permanently. For the time being, Germany. But looking forward to come a week or two before the conference to help out with everything what's needed.

**Comment by vvatikiotis** [comment]
Next Saturday we'll be interviewing a number of event organizers at Skroutz.gr  offices. The event is open to everyone. If you are planning to attend please inform us to notify Skroutz's security staff. 

Furthermore we informally meet for beers and whatever comes up every Wednesday at 9am at Tazzo, on Petraki street, alongside with the Appsterdam meetup. Depending on the mood and EuRuKo's priorities, we spent time discussing the conference's organisation issues. It's the time and place to be if you want to stay updated. Of course, everything is reported back to github's issues and to Ruby hellug forum.

**Comment by giedriusr** [comment]
:+1:

**Comment by chief** [comment]
Yep, attendance information is needed, please let us know

**Comment by nikosd** [comment]
We have event organizers and they are super :smile:
